apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nnhy25olo-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nnhy25olo-java-quarkus-gitops